config/routes.rb
ShareLinks::Application.routes.draw do
  resources :web_links do
    resources :comments, :only => [:create, :update, :destroy]
    resources :archive_links, :only => [:create, :destroy]
    collection do
      get :archived
    end
  end

  match '/sessions' => 'sessions#create', as: :sessions
  match '/logout' => 'sessions#destroy', as: :logout

  match '/style-guide' => 'home#style_guide'

  root :to => 'home#index'
end

app/models/archive_link.rb
class ArchiveLink < ActiveRecord::Base
  belongs_to :user
  belongs_to :web_link
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :web_link
  attr_accessible :body
  
  after_create :remove_archives

  validates :body, :presence => true 

  private

  # If a comment gets added, then it should be unarchived for both people.
  def remove_archives
    self.web_link.archive_links.each { |l| l.destroy }
    self.web_link.update_attribute(:archived, false)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :last_login, :name

  # archive_link objects that this user has created
  has_many :archive_links

  # Those weblinks which the user has archived.
  # This isn't currently used within the site.
  has_many :archived_web_links, through: :archive_links, source: :web_link, foreign_key: :web_link_id
  
  # Grab all the open links for a user.
  # This is an outer join in order to exclude 
  # archives performed by someone else. This is a very
  # complicated query.
  def open_links
    WebLink.where(archived: false).joins("LEFT OUTER JOIN archive_links ON archive_links.web_link_id = web_links.id AND archive_links.user_id = #{self.id}").where("archive_links.id IS NULL")
  end

end

app/models/web_link.rb
class WebLink < ActiveRecord::Base
  attr_accessible :url, :title, :comments_attributes

  has_many :archive_links
  has_many :comments
  belongs_to :user

  # Rejects a comment if it doesn't have a body.
  accepts_nested_attributes_for :comments, reject_if: lambda { |c| c[:body].blank? }

  # Grab all weblines that are acthived.
  scope :archived, lambda { where(:archived => true) }
 
  validates :url, :presence => true 

  # A weblink only gets archived if everyone in the system
  # has archived them. This method checks for that.
  def all_archived?
    self.archive_links.length == User.count
  end

  # Helper method to archive weblink
  def archive!
    self.update_attribute(:archived, true)
  end

  # Archives an archive_link for a given user
  # A user can't do this twice
  def archive(user)
    if self.archive_links.where(user_id: user.id).length == 0
      a = self.archive_links.create
      a.update_attribute(:user, user)
      
      self.archive! if all_archived?
    end
  end
 
  # Checks to see if a link is archived by a given user
  def archived_by?(user)
    !self.archive_links.where(user_id: user.id).empty?
  end

  # Helper method to check attribute
  def archived?
    self.archived
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  # Checks for current_user_id inside the session
  # if it is there then it sets @user, otherwise redirects
  def set_current_user
    if session[:current_user_id]
      @user = User.find(session[:current_user_id])
    else
      redirect_to root_url
    end
  end
end

app/controllers/archive_links_controller.rb
class ArchiveLinksController < ApplicationController
  before_filter :set_current_user

  # Not handling any error cases here
  def create
    @link = WebLink.find(params[:web_link_id])
    @link.archive(@user)

    respond_to do |format|
      format.html do
        if params[:archive_link]["redirect_to"] == 'index'
          redirect_to web_links_path
        else
          redirect_to link
        end
      end
      format.js
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :set_current_user

  def create
    @link = WebLink.find(params[:web_link_id])
    # building the comment through the link so we don't
    # have to have link_id attribute accessible
    @comment = @link.comments.build(params[:comment])
    @comment.user = @user
    if @comment.save
      redirect_to @link
    else
      flash[:error] = "There was an error saving the comment, please try again"
      # need an archive_link to render the page
      @archive_link = ArchiveLink.new
      render 'web_links/show'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Want to move the user to the weblinks index if they are signed in
  before_filter :redirect_user, except: [:style_guide]

  def index
    @users = User.all
  end

  def style_guide
    render :laout => :none
  end

  private

  def redirect_user
    redirect_to web_links_path if session[:current_user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    session[:current_user_id] = params[:user_id]
    redirect_to web_links_path
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_url
  end
end

app/controllers/web_links_controller.rb
class WebLinksController < ApplicationController
  before_filter :set_current_user

  def index
    @links = @user.open_links
    @link = WebLink.new
    @link.comments.build
  end

  def show
    @link = WebLink.find(params[:id])
    @comment = Comment.new
    @archive_link = ArchiveLink.new
  end

  def create
    @link = WebLink.new(params[:web_link])
    # If a comment was created with link, then we want to set
    # the user of the comment (since it isn't attribute accessible)
    @link.comments.first.user = @user unless @link.comments.empty?
    @link.user = @user
    if @link.save
      redirect_to web_links_path
    else
      flash[:error] = "Couldn't save"
      # need to set the same variables that index does so the 
      # view can render.
      @links = @user.open_links
      @link.comments.build if @link.comments.empty?
      render :index # index has the form for a new web link
    end
  end

  def destroy
    link = WebLink.find(params[:id])
    link.destroy
    redirect_to web_links_path
  end

  def archived
    @links = WebLink.archived
    @user_archived = @user.archived_web_links.where(archived: false)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Method to format time.
  def simple_time(time)
    # 3:45pm Tue, Jan 3
    time.strftime("%l:%M%P %a, %b %-d")
  end
  
  # Present errors for a form
  def show_errors(obj)
    return_string = "<div class='errors'><p>There were some errors:</p><ul>"
    obj.errors.each do |key, value|
     return_string += "<li>#{key.capitalize} #{value}</li>"
    end
    return_string += "</ul></div>"
    return_string.html_safe
  end
end

app/helpers/archive_links_helper.rb
module ArchiveLinksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/web_links_helper.rb
module WebLinksHelper
end

app/views/archive_links/create.js.erb
$(".js-article-<%= @link.id %>").slideUp();

app/views/home/index.html.erb
<h1>Pick Yourself</h1>


<% @users.each do |user| %>
  <%= form_tag sessions_path do %>
    <%= hidden_field_tag :user_id, user.id %>
    <%= submit_tag user.name %>
  <% end %>
<% end %>

app/views/home/style_guide.html.erb
<h1>Header 1</h1>
<p>Default paragraph</p>
<h2>Header 2</h2>
<p>Default paragraph</p>
<h3>Header 3</h3>
<p>Default paragraph</p>
<h4>Header 4</h4>
<p>Default paragraph</p>

<p>Default paragraph. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada, magna sed venenatis gravida, sem libero dignissim eros, nec volutpat sapien tortor ut ligula. In hac habitasse platea dictumst.</p>

<input type="text" name="" id="" value="" />

<input type="submit" name="" id="" value="Submit Article" />

<article>
  <cite><a href="#">Title of Article</a></cite>
  <div class="author">Ryan Mathews (5 comments)</div>
  <div class="comment">
    <p>Description / comment about the article. Usually pretty short, but could wrap lines.</p>
    <span>Ryan Mathews</span>
  </div>
</article>

<h2>Comments</h2>

<div class="comments">
  <div class="comment">
    <p>Description / comment about the article. Usually pretty short, but could wrap lines.</p>
    <span>Ryan Mathews</span>
  </div>
  <div class="comment">
    <p>Description / comment about the article. Usually pretty short, but could wrap lines.</p>
    <span>Ryan Mathews</span>
  </div>
  <div class="comment">
    <p>Description / comment about the article. Usually pretty short, but could wrap lines.</p>
    <span>Ryan Mathews</span>
  </div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShareLinks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <link href='http://fonts.googleapis.com/css?family=Cantarell:400,400italic|Playfair+Display+SC:400,900,700' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <nav>
    <ul>
      <li><%= link_to "All Links", web_links_path %></li>
      <li><%= link_to "Archived", archived_web_links_path %></li>
      <% if @user %>
        <li><%= link_to "Logout", logout_path %></li>
      <% end %>
    </ul>
  </nav>

  <%= yield %>
</div>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShareLinks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <link href='http://fonts.googleapis.com/css?family=Cantarell:400,400italic|Playfair+Display+SC:400,900,700' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <nav>
    <ul>
      <li><%= link_to "All Links", web_links_path %></li>
      <li><%= link_to "Archived", archived_web_links_path %></li>
      <li><%= link_to "Sign In", root_path %></li>
      <% if @user %>
        <li><%= link_to "Logout", logout_path %></li>
      <% end %>
    </ul>
  </nav>

  <%= yield %>

</div>


</body>
</html>

app/views/web_links/_web_link.html.erb
<article class="js-article-<%= web_link.id %>">
<cite><%= link_to web_link.title, web_link %> (<%= link_to "link", web_link.url %>)</cite>
<div class="author">
  <%= web_link.user.name %> - 
  <%= time_ago_in_words(web_link.created_at) %> ago 
  (<%= pluralize web_link.comments.count, "comment" %>) - 
  <% if web_link.archived_by?(@user) %>
    Archived
  <% else %>
    <%= form_for [web_link, ArchiveLink.new], remote: true do |f| %>
      <%= f.hidden_field :redirect_to, value: "index" %>
      <%= link_to "Archive", '#', class: "js-submit" %>
    <% end %>
  <% end %>
</div>
<% if !web_link.comments.empty? %>
  <div class="comment">
    <p><%= web_link.comments.last.body %></p>
    <span><%= web_link.comments.last.user.name %></span>
  </div>
<% end %>

</article>  

app/views/web_links/archived.html.erb
<h1>Archived Links</h1>
<ul>
  <% @links.each do |link| %>
    <li><%= link_to link.title, link %> (submitted by: <%= link.user.name %>, last comment by: <%= link.comments.last.user.name unless link.comments.empty? %>)</li>
  <% end %>
</ul>

<% unless @user_archived.empty? %>
  <h1>Your Archived Links</h1>
  <p>(Not archived yet)</p>
  <ul>
    <% @user_archived.each do |link| %>
      <li><%= link_to link.title, link %> (submitted by: <%= link.user.name %>, last comment by: <%= link.comments.last.user.name unless link.comments.empty? %>)</li>
    <% end %>
  </ul>
<% end %>

app/views/web_links/index.html.erb
<h1>Recent Links</h1>

<p>Welcome back <%= @user.name %></p>

<div class="new-link">
  <h3>Share New Link</h3>
  <%= form_for @link do |f| %>
    <%= show_errors(@link) unless @link.errors.empty? %>
    <div class="control">
      <%= f.label :title %>
      <%= f.text_field :title, autocomplete: 'off', placeholder: 'Title' %>
    </div>
    <div class="control">
      <%= f.label :url, "Address" %>
      <%= f.text_field :url, autocomplete: 'off', placeholder: 'http://...' %>
    </div>
    <%= f.fields_for :comments do |comment| %>
      <div class="control">
        <%= comment.label :body, "Comment" %>
        <%= comment.text_area :body, size: "30x2", placeholder: 'Comment' %>
      </div>
    <% end %>
    <div class="control submit">
      <%= f.submit "Add Link" %>
    </div>
  <% end %>
</div>

<div class="links">
  <%= render @links || "No unread links" %>
</div>

app/views/web_links/show.html.erb
<div class="header">

  <h1><%= link_to @link.title, @link.url, :target => "_blank" %></h1>

  <div class="controls">
    <%= link_to "Delete", @link, method: :delete if @link.user == @user %>
    <% if @link.archived_by?(@user) %>
      Archived
    <% else %>
      <%= form_for [@link, @archive_link] do |f| %>
        <%= link_to "Archive", '#', class: "js-submit" %>
      <% end %>
    <% end %>
  </div>

</div>

<div class="new-comment">
  <%= form_for [@link, @comment] do |f| %>
    <%= show_errors(@comment) unless @comment.errors.empty? %>
    <div class="control">
      <%= f.label :body, "Comment" %>
      <%= f.text_area :body, size: "30x3" %><br/>
    </div>
    <div class="control submit">
      <%= f.submit "Comment" %>
    </div>
  <% end %>
</div>

<div class="archives">
  <% @link.archive_links.each do |archive_link| %>
    <span>
      Archived by <%= archive_link.user.name %> on <%= simple_time archive_link.created_at %>
    </span>
    <br/>
  <% end %>
</div>

<div class="comments">
  <% @link.comments.each do |comment| %>
    <div class="comment">
      <p><%= comment.body %></p>
      <span><%= comment.user.name %></span>
    </div>
  <% end %>
</div>